stages:
  - deploy

deploy:
  stage: deploy
  image: bitnami/minideb
  before_script:
    - apt-get update
    - apt-get install -y git ruby ruby-dev nodejs npm curl
    - gem install dpl
  script:
    - cd server
    - dpl --provider=heroku --app=sound-ify --api-key=$HEROKU_API_KEY
  only:
    - master